title: Hidden Collections Africa
shortname: Hidden Collections Africa
description: ''

permalink: pretty

baseurl: /hca

# https://github.com/jekyll/jekyll-sass-converter
sass:
    style: expanded #compressed